### ISSUE TITLE
Version 1.54 fails to build with libguestfs 1.58.1

### ISSUE THREAD

**Issue by mohd-akram** [libguestfs/guestfs-tools#28]
I'm not sure how to sync the versions, since there hasn't been a new stable release of guestfs-tools. I'm getting this error when building:

```c
structs-print.c:66:63: error: no member named 'app2_spare1' in 'struct guestfs_application2'
   66 |   fprintf (dest, "%sapp2_spare1: %s%s", indent, application2->app2_spare1, linesep);
      |                                                 ~~~~~~~~~~~~  ^
1 error generated.
```

**Comment by mohd-akram** [comment]
Closing since a new stable release is out.
